spring:
    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false
    data:
        redis:
            url: ${REDIS_URL}
            database: 7
    liquibase:
        enabled: true

logging:
    level:
        com.backandwhite: INFO
        org.springframework: WARN
